// react/src/components/Balance.js
import React, {Component} from 'react';

import Ball from './Ball';
import Result from './Result';
import {compute} from '../services/compute';

import './Balance.css';

class Balance extends Component {
    constructor(props) {
        super(props);
        this.state = this._getDefaultState();

        this.handleBallClick = this.handleBallClick.bind(this);
        this.reset = this.reset.bind(this);
        this.findBall = this.findBall.bind(this);
    }

    _getDefaultState() {
        return {
            result: false,
            error: false,
            balls: this._getDefaultBalls()
        }
    }

    _generateBall(index, weight = this.props.defaultWeight) {
        return {
            index,
            weight
        }
    }

    _getDefaultBalls() {
        return Array.from(Array(this.props.ballsCount).keys()).map(i => this._generateBall(i));
    }

    handleBallClick(ball) {
        const balls = this._getDefaultBalls();
        balls[ball.index].weight = this.props.defaultWeight * 2;
        this.setState({
            error: null,
            balls
        });
    }

    reset() {
        this.setState(this._getDefaultState());
    }

    findBall() {
        this.setState({
            result: compute(this.state.balls)
        });
    }

    render() {
        const balls = this.state.balls.map(ball => (
            <Ball key={ball.index} id={ball.index} ball={ball} selected={ball.weight !== this.props.defaultWeight}
                  handleClick={this.handleBallClick}/>
        ));

        return (
            <div className="balance">
                <div className="balls">
                    {balls}
                </div>
                <div className="row">
                    <div className="controls">
                        <button className="button reset" onClick={this.reset}>Reset</button>
                        <button className="button run" onClick={this.findBall}>Run</button>
                    </div>
                </div>
                {
                    this.state.error ? (
                            <div className="error">
                                {this.state.error}
                            </div>
                        ) : ''
                }
                {
                    this.state.result ? (
                            <Result result={this.state.result}/>
                        ) : ''
                }
            </div>
        );
    }
}

Balance.propTypes = {
    ballsCount: React.PropTypes.number,
    defaultWeight: React.PropTypes.number
};

export default Balance;

// angular2/src/app/components/balance.component.ts
import {Component, Input, OnInit} from '@angular/core';

import {Ball} from './ball';
import {compute} from '../services/computer.service';

@Component({
  moduleId: module.id,
  selector: 'balance',
  templateUrl: './balance.component.html',
  styleUrls: ['./balance.component.css']
})
export class BalanceComponent implements OnInit {
  @Input()
  ballsCount: number;

  defaultWeight = 10;
  balls: Ball[] = [];
  selectedBall: Ball;
  error: String;
  result: any;

  ngOnInit(): void {
    this.balls = Array.from(Array(this.ballsCount).keys()).map(i => this._generateBall(i));
  }

  _generateBall(index: number, weight: number = this.defaultWeight) {
    return {
      index,
      weight
    }
  }

  _resetBalls() {
    this.balls.forEach((b, i) => this.balls[i].weight = this.defaultWeight);
  }

  onSelect(ball: Ball): void {
    this.error = null;
    this.selectedBall = ball;
    this._resetBalls();
    this.balls[ball.index].weight = this.defaultWeight * 2;
  }

  reset() {
    this.selectedBall = null;
    this.error = null;
    this.result = null;
    this._resetBalls();
  }

  findBall() {
    if (!this.selectedBall) {
      this.error = "Please choose a ball first";
      return;
    }

    this.result = compute(this.balls);
  }
}

<div class="balance">
  <div class="balls">
    <div class="ball"
         *ngFor="let ball of balls"
         [class.selected]="ball === selectedBall"
         (click)="onSelect(ball)">
      <span class="index">{{ball.index + 1}}</span>
      <span class="weight">{{ball.weight}}</span>
    </div>
  </div>
  <div class="row">
    <div class="controls">
      <button class="button reset" (click)="reset()">Reset</button>
      <button class="button run" (click)="findBall()">Run</button>
    </div>
  </div>
  <div class="error" *ngIf="error">
    {{error}}
  </div>
  <div class="result" *ngIf="result">
    <h3>Results</h3>
    <p>Ball {{result.ball.index + 1}} is the heaviest !</p>
    <p>Found in {{result.round}} rounds.</p>
  </div>
</div>
