// angular2/src/app/app.component.ts
import {Component} from '@angular/core';

@Component({
  moduleId: module.id,
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  name = 'Roberval Balance';
  ballsCount = 8;
}

<div class="app">
  <header class="header">
    <img class="logo" src="assets/images/balance.png" alt="logo">
    <h2>{{name}}</h2>
  </header>
  <balance [ballsCount]="ballsCount"></balance>
</div>

// react/src/components/App.js
import React, {Component} from 'react';

import Balance from './Balance';

import './App.css';

class App extends Component {
    render() {
        return (
            <div className="app">
                <header className="header">
                    <img className="logo" src="/images/balance.png" alt="balance"/>
                    <h2>Roberval Balance</h2>
                </header>
                <Balance ballsCount={8} defaultWeight={10}/>
            </div>
        );
    }
}

export default App;
